# Generated by Django 2.1.3 on 2018-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_make_email_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.TextField(null=True),
        ),
    ]
